---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with yum
  yum:
   name: kibana
   update_cache: yes
 
# Configurations

- name: Updating the config file to allow outside access
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: "10.175.5.171"'

- name: Defining server port
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: 5601'
    
- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'logging.dest:'
   line: 'logging.dest: /var/log/kibana/kibana.log'

- name: Defining Elasticsearch URL
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.hosts:'
   line: 'elasticsearch.hosts: ["http://localhost:9200"]'

- name: Check Kibana service added to firewalld
  firewalld:
    service: kibana
    state: enabled
    permanent: yes
    immediate: yes

- name: Check port 5601 added to firewalld
  firewalld:
    port: 5601/tcp
    state: enabled
    permanent: yes
    immediate: yes
   
# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
